import Link from "next/link";
import { ArrowRight, Check, Code2, LockKeyhole, QrCode, ShieldCheck, Sparkles } from "lucide-react";

const links = [["Quickstart", "/quickstart"], ["Backup guide", "/otpbackup"], ["Privacy", "/privacy"]];
export default function Home() { return <main><SiteHeader /><section className="hero shell"><div className="hero-copy"><p className="eyebrow"><Sparkles size={15} /> Your codes, under your control</p><h1>Simple 2FA.<br /><span>Built for your browser.</span></h1><p className="lead">AuthX keeps your one-time verification codes close, private, and ready when you need them.</p><div className="actions"><a className="button primary" href="https://github.com/NanoKillX/AuthX" target="_blank" rel="noreferrer"><Code2 size={18} /> View source</a><Link className="button ghost" href="/quickstart">Get started <ArrowRight size={17} /></Link></div><div className="trust-line"><Check size={15} /> Works locally in your browser <span>•</span> Follows your system theme</div></div><div className="vault-preview" aria-label="AuthX extension preview"><div className="preview-top"><Brand /><span className="mini-badge">2FA</span><button aria-label="Settings">⚙</button></div><div className="preview-code"><div><span>GitHub</span><strong>184 026</strong></div><span className="ring" /></div><div className="preview-code"><div><span>Google</span><strong>731 842</strong></div><span className="ring purple" /></div><button className="add-account"><span>+</span> Add account</button></div></section><section className="shell feature-grid"><Feature icon={<QrCode />} title="Add in seconds" text="Scan a QR code, enter a key, or bring in your existing OTP links." /><Feature icon={<LockKeyhole />} title="Keep your vault yours" text="Lock your accounts, make an encrypted backup, and restore when you need to." /><Feature icon={<ShieldCheck />} title="Stay in control" text="Clear guidance for permissions, browser support, and keeping your codes safe." /></section><section className="shell getting-started"><div><p className="eyebrow">Getting started</p><h2>Your first code is only a few steps away.</h2></div><ol><li><b>1</b><span>Install AuthX in your browser.</span></li><li><b>2</b><span>Add an account with a QR code or setup key.</span></li><li><b>3</b><span>Save an encrypted backup for peace of mind.</span></li></ol><Link className="text-link" href="/quickstart">Open the quickstart <ArrowRight size={17} /></Link></section><Footer /></main>; }
export function Brand() { return <Link href="/" className="brand"><span className="brand-mark">✕</span><span>AuthX</span></Link>; }
export function SiteHeader() { return <header className="site-header shell"><Brand /><nav>{links.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</nav><a className="header-github" href="https://github.com/NanoKillX/AuthX" target="_blank" rel="noreferrer"><Code2 size={17} /><span>GitHub</span></a></header>; }
export function Footer() { return <footer className="shell"><Brand /><div><Link href="/privacy">Privacy</Link><a href="https://github.com/NanoKillX/AuthX" target="_blank" rel="noreferrer">Source code</a></div><p>Created by NanoKillX</p></footer>; }
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="feature-card"><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{text}</p></article>; }
